PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX dbpprop: <http://dbpedia.org/property/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX edgar: <http://edgarwrap.ontologycentral.com/vocab/edgar#>
PREFIX us-gaap2009: <http://edgarwrap.ontologycentral.com/vocab/us-gaap-2009-01-31#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX measure: <http://purl.org/linked-data/sdmx/2009/measure#>
PREFIX ical: <http://www.w3.org/2002/12/cal/ical#>

SELECT ?bankSEC ?personnelCosts ?dateBegin1 ?dateEnd1 ?nonInterestIncome ?dateBegin2 ?dateEnd2 WHERE {
?bankSEC edgar:issued ?facts .

?facts rdfs:seeAlso ?bn1 .
?facts rdfs:seeAlso ?bn2 .

?bn1 edgar:subject us-gaap2009:LaborAndRelatedExpense .
?bn1 measure:obsValue ?personnelCosts .
?bn1 ical:dtstart ?dateBegin1 .
?bn1 ical:dtend ?dateEnd1 .

?bn2 edgar:subject us-gaap2009:NoninterestIncome .
?bn2 measure:obsValue ?nonInterestIncome .
?bn2 ical:dtstart ?dateBegin2 .
?bn2 ical:dtend ?dateEnd2 .
}