PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX dbpprop: <http://dbpedia.org/property/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX edgar: <http://edgarwrap.ontologycentral.com/vocab/edgar#>
PREFIX us-gaap2009: <http://edgarwrap.ontologycentral.com/vocab/us-gaap-2009-01-31#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX measure: <http://purl.org/linked-data/sdmx/2009/measure#>
PREFIX ical: <http://www.w3.org/2002/12/cal/ical#>
PREFIX ab: <http://alexander-buescher.org/vocab/>

SELECT DISTINCT ?db ?loc ?bankSEC ?revenues1 ?revenues2 ?revenues3 WHERE {

?bankSEC ab:linked ?db .
?bankSEC edgar:cikNumber "35527" .
?db dbpedia-owl:numberOfLocations ?loc .
?bankSEC edgar:issued ?facts .

?facts rdfs:seeAlso ?bn1 .

?bn1 edgar:subject us-gaap2009:InterestAndDividendIncomeOperating .
?bn1 measure:obsValue ?revenues1 .
?bn1 ical:dtstart "2008-01-01"^^<http://www.w3.org/2001/XMLSchema#date> .
?bn1 ical:dtend "2008-09-30"^^<http://www.w3.org/2001/XMLSchema#date> .

?bn2 edgar:subject us-gaap2009:InterestAndDividendIncomeSecurities .
?bn2 measure:obsValue ?revenues2 .
?bn2 ical:dtstart "2008-01-01"^^<http://www.w3.org/2001/XMLSchema#date> .
?bn2 ical:dtend "2008-09-30"^^<http://www.w3.org/2001/XMLSchema#date> .

?bn3 edgar:subject us-gaap2009:InterestAndFeeIncomeLoansAndLeases .
?bn3 measure:obsValue ?revenues3 .
?bn3 ical:dtstart "2008-01-01"^^<http://www.w3.org/2001/XMLSchema#date> .
?bn3 ical:dtend "2008-09-30"^^<http://www.w3.org/2001/XMLSchema#date> .
}