PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX dbpprop: <http://dbpedia.org/property/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX edgar: <http://edgarwrap.ontologycentral.com/vocab/edgar#>
PREFIX us-gaap2009: <http://edgarwrap.ontologycentral.com/vocab/us-gaap-2009-01-31#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX measure: <http://purl.org/linked-data/sdmx/2009/measure#>
PREFIX ical: <http://www.w3.org/2002/12/cal/ical#>
PREFIX ab: <http://alexander-buescher.org/vocab/>
PREFIX yhof: <http://yahoofinancewrap.appspot.com/vocab/yahoo#>
PREFIX dcterms: <http://purl.org/dc/terms/>

SELECT DISTINCT ?bankSEC ?changeInProfits ?yh ?stockStart ?stockEnd WHERE {

?bankSEC edgar:cikNumber "35527" .
?bankSEC ab:linked ?yh .

?bankSEC edgar:issued ?facts .
?facts rdfs:seeAlso ?bn .
?bn edgar:subject us-gaap2009:NetIncomeLoss .
?bn measure:obsValue ?changeInProfits .
?bn ical:dtstart "2009-01-01"^^<http://www.w3.org/2001/XMLSchema#date> .
?bn ical:dtend "2009-03-31"^^<http://www.w3.org/2001/XMLSchema#date> .

?bny2 yhof:issuer ?yh .
?bny2 measure:obsValue ?stockStart .
?bny2 dcterms:date "2009-01-02"^^<http://www.w3.org/2001/XMLSchema#date> .
?bny2 yhof:subject <http://yahoofinancewrap.appspot.com/vocab/stock#Close> .

?bny3 yhof:issuer ?yh .
?bny3 measure:obsValue ?stockEnd .
?bny3 dcterms:date "2009-03-31"^^<http://www.w3.org/2001/XMLSchema#date> .
?bny3 yhof:subject <http://yahoofinancewrap.appspot.com/vocab/stock#Close> .
}
