PREFIX dbpedia-owl: <http://dbpedia.org/ontology/>
PREFIX dbpprop: <http://dbpedia.org/property/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX edgar: <http://edgarwrap.ontologycentral.com/vocab/edgar#>
PREFIX us-gaap2009: <http://edgarwrap.ontologycentral.com/vocab/us-gaap-2009-01-31#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX measure: <http://purl.org/linked-data/sdmx/2009/measure#>
PREFIX ical: <http://www.w3.org/2002/12/cal/ical#>
PREFIX ab: <http://alexander-buescher.org/vocab/>

SELECT ?bankSEC ?db ?parent ?parentLoc ?parentEmp ?sub ?subLoc ?subEmp WHERE {
?bankSEC ab:linked ?db .
{
{ ?db dbpprop:parent ?parent . }
OPTIONAL
{?parent dbpedia-owl:numberOfEmployees ?parentEmp .
?parent dbpedia-owl:location ?parentLoc .}
}
UNION
{
{?sub dbpprop:parent ?db .}
OPTIONAL
{?sub dbpedia-owl:numberOfEmployees ?subEmp .
?sub dbpedia-owl:location ?subLoc .}
}
}
